### PR TITLE
Clossing issues #17, #15, #14, #13, #12, #11, #10, #9 and #8

### LINKED ISSUE #8: Refactor needed for CompanyController#store()
The method should be rewritten with cleaner code and better application of DRY.

This is just a refactoring, so the behavior of the method should not be changed.

Proper linting rules (consistent-return) should be also followed.

### LINKED ISSUE #9: CompanyController#rankUserOnCompany() is not responding with the appropriate HTTP response codes
HTTP 403 (Forbidden) is being used for restricted operations. These operations arise from errors in the data, or unexpected behavior by the user, to HTTP 400 (Bad Request) should be used instead.

### LINKED ISSUE #10: CompanyController#rankUserOnCompany() doesn't assign proper ranks
In the DB schema for _UserCompany_, _rank_ is intended to be a integer (and the middleware checks for an integer too), yet _rankUserOnCompany()_ passes string values to it. Who knows how this doesn't end in an error.

### LINKED ISSUE #11: CompanyController#rankUserOnCompany() is not integrated with the CheckUserCompanyPermission middleware
As of right now, the route for _rankUserOnCompany()_ is public. It should be restricted to the appropriate rank level.

### LINKED ISSUE #12: OfferController responding with exceptions
_OfferController_ should make use of appropriate try-catch blocks and return correct HTTP codes instead of letting Adonis handle it.

This is maybe not 100% necessary, so it should be discussed first.

### LINKED ISSUE #13: OfferController#getAllOffers() should offer paginated results
Check _OfferController#getAllPublicOffers()_ for reference.

### LINKED ISSUE #14: OfferController#store() not returning appropriate HTTP response code on offer creation
Currently HTTP 204 (No Content) is being returned. Change this to return HTTP 201 (Created) instead.

### LINKED ISSUE #15: UserController#genTokenToRecoverPassword() returning HTTP 401 if user email is not found.
It should return HTTP 404 instead, since it's looking for data that doesn't exist.

### LINKED ISSUE #17: CompanyController#inviteToCompany() returns HTTP 403 on email sending failure
It should return a more appropriate code by checking the SMTP error. Probably either HTTP 500, HTTP 401 or HTTP 400.

### PR DESCRIPTION
**Pull request by SamuelRiveraC**
Fixing Issues after the first pull request, our old code was lingering there waiting for fixes we are working on right now. @hniklass merged 2 pull requests and fixed most of the issues. 

Listing: 
OfferController#getAllOffers() should offer paginated results: Applied a post input called "page" same as the method below
OfferController responding with exceptions: Added a try catch around the most likely place to get errors, the OfferController#store

CompanyController#rankUserOnCompany() is not integrated with the CheckUserCompanyPermission middleware: Applied correctly the Middleware at the route
CompanyController#rankUserOnCompany() doesn't assign proper ranks: added parseInt to ensure saving it as an integer (but I agree it is weird that it didn't fail before)
CompanyController#rankUserOnCompany() is not responding with the appropriate HTTP response codes: Responses code were corrected to BadRequest or NotFound as recommended

For: OfferController#store() not returning appropriate HTTP response code on offer creation, UserController#genTokenToRecoverPassword() returning HTTP 401 if user email is not found: , CompanyController#inviteToCompany() returns HTTP 403 on email sending failure: 
Fixed I changed the response

### CODE REVIEW

File: app/Controllers/Http/companies/CompanyController.js [hunk 1]
```diff
@@ -49,36 +49,30 @@ class CompanyController {
...
+    }
 
-      const storedCompany = await Company.create(company);
+    try {
+      if (!company) {
+        const user = await auth.getUser();
+        const storedCompany = await Company.create(company);
 
-      if (await user.companies().attach([user.id, storedCompany.id], null)) {
+        await user.companies().attach([user.id, storedCompany.id], null);
```
Comment (hniklass) [inline app/Controllers/Http/companies/CompanyController.js:68]: This store method doesn't go through the UserCompanyRank middleware. It allows anyone with a company name (what about repeated company names btw?) to modify any company, whether they're a part of it or not, whether they have rank or not.

These functions should be separated.

File: app/Controllers/Http/companies/CompanyController.js [hunk 2]
```diff
@@ -121,9 +115,10 @@ class CompanyController {
 
     if (!company) {
       return response.notFound('This company could not be found');
-    }// else if (company.offers_count > 0 ){
-    //  return response.forbidden('This company has active offers')
-    // }
+    }
+    if (company.offers_count > 0) {
+      return response.forbidden('This company has active offers');
```
Comment (hniklass) [inline app/Controllers/Http/companies/CompanyController.js:120]: This should be 400.

File: app/Controllers/Http/companies/CompanyController.js [hunk 3]
```diff
@@ -134,55 +129,49 @@ class CompanyController {
...
+   * @version 0.1 (0.1.0-alpha.r8)
    * @param {Object(auth, request, response)} ctx - The context object.
    * @returns {HTTP200|JSON}
    * @returns {HTTP200|JSON}
-   * @returns {HTTP403|JSON}
-   * @returns {HTTP403|JSON}
-   * @returns {HTTP403|JSON}
-   * @returns {HTTP403|JSON}
+   * @returns {HTTP404|JSON}
+   * @returns {HTTP500|JSON}
```
Comment (hniklass) [inline app/Controllers/Http/companies/CompanyController.js:172]: These should be 400.

**Review by hniklass — CHANGES_REQUESTED** [review]

**Review by hniklass — APPROVED** [review]
